config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  get "/dashboard", to: "users#show"
  get "auth/github", as: :github_login
  get "auth/github/callback", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider      = auth["provider"]
      user.uid           = auth["uid"]
      user.name          = auth["info"]["name"]
      user.username      = auth["info"]["nickname"]
      user.image_path    = auth["info"]["image"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if user = User.create_with_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to dashboard_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Welcome to Github Curious</h1>

<div class="well col-md-4 col-md-offset-4">
  <% if current_user %>
    Hi there, <%= current_user.name %>
    <%= link_to "Logout", logout_path, method: :delete %>
  <% else %>
    <%= link_to "Sign in with Github", github_login_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubCurious</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/show.html.erb
<h1><%= @user.name %></h1>

<div class="user_info">
  <p>
    <%= image_tag(@user.image_path, class: 'img-thumbnail') %>
  </p>
  <p>
    Username: <%= @user.username %>
  </p>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<div class="user_info">
  <p>
    <%= image_tag(@user.image_path, class: 'img-thumbnail') %>
  </p>
  <p>
    Username: <%= @user.username %>
  </p>
</div>